package:
    type:           yii2-extension
    name:           hiam-mrdp
    title:          HIAM module for MRDP database compatibility
    headline:       HIAM MRDP
    keywords:       hiam, mrdp
    namespace:      hiam\mrdp
    description:    |
        [HIAM](https://github.com/hiqdev/hiam-core) is Identity and Access Management server.

        This package provides MRDP database compatibility classes:

        - Identity model with seller and seller_id
        - Client storage model with ClientQuery
